api_version = "2023-10"

[[extensions]]
handle = "shipping-discount"
name = "Shipping Discount"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
